baseURL = 'https://nelsonsaake.github.io/mcs-docs'
languageCode = 'en-us'
title = 'mcs-docs'
theme = 'ananke'

paginate = '20'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.postCSS]
    config = "postcss.config.js"
    includePaths = ["assets/css"]

[params]
  [params.ananke]
    social = []
